/**
 * Minecraft 导出工坊与指令生成模块
 * 支持导出 PNG、Minecraft 指令、.mcfunction 文件以及生存材料清单
 */

export class ExportStudio {
  /**
   * 导出 Canvas 为 PNG 图片并下载
   */
  static downloadCanvas(canvas, filename = 'minecraft-art.png') {
    if (!canvas) return;
    const link = document.createElement('a');
    link.download = filename;
    link.href = canvas.toDataURL('image/png');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  /**
   * 生成 Minecraft /setblock 指令序列
   * @param {Object} gridResult 像素结果
   * @param {string} orientation 'wall_xy' (立在墙上) 或 'floor_xz' (铺在地上)
   * @param {number} startX 起始相对坐标
   * @param {number} startY 起始相对坐标
   * @param {number} startZ 起始相对坐标
   */
  static generateMinecraftCommands(gridResult, { orientation = 'wall_xy', startX = 0, startY = 0, startZ = 0 } = {}) {
    if (!gridResult || !gridResult.grid) return '';

    const { width, height, grid } = gridResult;
    const commands = [];
    commands.push(`# Minecraft Pixel Art Generated By Minecraft Picture Studio`);
    commands.push(`# Size: ${width}x${height}, Total Blocks: ${width * height}`);
    commands.push(``);

    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        const block = grid[y][x];
        const blockId = `minecraft:${block.id}`;

        let targetX, targetY, targetZ;
        if (orientation === 'wall_xy') {
          // 立面墙 (从左到右，从下到上)
          targetX = `~${startX + x}`;
          targetY = `~${startY + (height - 1 - y)}`;
          targetZ = `~${startZ}`;
        } else {
          // 平铺地面 (从左到右，从上到下)
          targetX = `~${startX + x}`;
          targetY = `~${startY}`;
          targetZ = `~${startZ + y}`;
        }

        commands.push(`setblock ${targetX} ${targetY} ${targetZ} ${blockId}`);
      }
    }

    return commands.join('\n');
  }

  /**
   * 下载为 .mcfunction 文件
   */
  static downloadMcFunction(commandsText, filename = 'build_art.mcfunction') {
    const blob = new Blob([commandsText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * 生成生存建造材料清单
   */
  static generateMaterialsList(usedBlocks) {
    if (!usedBlocks) return [];
    return usedBlocks.map(block => {
      const stacks = Math.floor(block.count / 64);
      const remaining = block.count % 64;
      let stackStr = '';
      if (stacks > 0) {
        stackStr = `${stacks} 组 ${remaining > 0 ? remaining + ' 个' : ''}`;
      } else {
        stackStr = `${remaining} 个`;
      }

      return {
        id: block.id,
        name: block.name,
        count: block.count,
        stackDesc: stackStr,
        hex: block.hex
      };
    });
  }
}
